### ISSUE TITLE
DataFrames code has listed these methods as common to abstractdataframes

### ISSUE THREAD

**Issue by xiaodaigh** [queryverse/TableTraits.jl#1]
Should TableTraits be implementing all these functions?

> **Common methods**
> An AbstractDataFrame is a two-dimensional table with Symbols for
> column names. An AbstractDataFrame is also similar to an Associative
> type in that it allows indexing by a key (the columns).
> The following are normally implemented for AbstractDataFrames:
> * [`describe`](@ref) : summarize columns
> * [`dump`](@ref) : show structure
> * `hcat` : horizontal concatenation
> * `vcat` : vertical concatenation
> * `names` : columns names
> * [`names!`](@ref) : set columns names
> * [`rename!`](@ref) : rename columns names based on keyword arguments
> * [`eltypes`](@ref) : `eltype` of each column
> * `length` : number of columns
> * `size` : (nrows, ncols)
> * [`head`](@ref) : first `n` rows
> * [`tail`](@ref) : last `n` rows
> * `convert` : convert to an array
> * [`completecases`](@ref) : boolean vector of complete cases (rows with no nulls)
> * [`dropnull`](@ref) : remove rows with null values
> * [`dropnull!`](@ref) : remove rows with null values in-place
> * [`nonunique`](@ref) : indexes of duplicate rows
> * [`unique!`](@ref) : remove duplicate rows
> * `similar` : a DataFrame with similar columns as `d`

**Comment by davidanthoff** [comment]
That is not the idea of this interface here. The interface here is an absolute minimal interface for tables to interop, with nothing user facing, the idea is that this really enables interop between different packages and that users never see this.
